---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "debeziumserver-cluster-role"
rules:
- apiGroups:
  - "debezium.io"
  resources:
  - "debeziumservers"
  - "debeziumservers/status"
  - "debeziumservers/finalizers"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "create"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
